// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelExperts.DataAccess.Models;

public partial class Customer
{
    public int CustomerId { get; set; }

    public string CustFirstName { get; set; }

    public string CustLastName { get; set; }

    public string CustAddress { get; set; }

    public string CustCity { get; set; }

    public string CustProv { get; set; }

    public string CustPostal { get; set; }

    public string CustCountry { get; set; }

    public string CustHomePhone { get; set; }

    public string CustBusPhone { get; set; }

    public string CustEmail { get; set; }

    public int? AgentId { get; set; }
}